apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      nodeSelector:
        node13: "yes"
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.path }}:{{ .Values.app.version }}"
          resources:
{{ toYaml .Values.resources | indent 12 }}
          imagePullPolicy: Always
          env:
            - name: DB_NAME
              value: postgres
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: password
            - name: DB_HOST
              value: "10.110.248.73"
            - name: DB_PORT
              value: "5432"
